apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Release.Namespace }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Release.Namespace }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.name }}-{{ .Release.Namespace }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          livenessProbe:
            httpGet:
              path: /usr/share/nginx/html
              port: 80
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 15
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.api.enabled }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
