apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name}}-{{ .Release.Namespace }}-clusterip
spec:
  type: ClusterIP
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.name}}-{{ .Release.Namespace }} 
